---
kubernetes:
  children:
    master:
      hosts:
        k8s0:
          ansible_host: 192.168.10.200
        k8s1:
          ansible_host: 192.168.10.201
        k8s2:
          ansible_host: 192.168.10.202
    worker:
      hosts:
        k8s3:
          ansible_host: 192.168.10.203
        k8s4:
          ansible_host: 192.168.10.204
